import fs from 'fs';
import path from 'path';
import Link from 'next/link';
import { BookOpen, Clock, ChevronRight, Zap, Archive } from 'lucide-react';

async function getLatestProblem() {
  const problemsDir = path.join(process.cwd(), 'TOEIC', '問題');
  if (!fs.existsSync(problemsDir)) {
    return null;
  }
  const files = fs.readdirSync(problemsDir)
    .filter(file => file.endsWith('.json'))
    .map(file => {
      const filePath = path.join(problemsDir, file);
      const stats = fs.statSync(filePath);
      return { file, mtime: stats.mtime };
    })
    .sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

  if (files.length === 0) return null;
  return files[0].file.replace('.json', '');
}

export default async function Dashboard() {
  const latestProblemId = await getLatestProblem();

  return (
    <main className="min-h-screen bg-slate-50 font-sans text-slate-800">
      {/* Hero Section */}
      <div className="bg-indigo-600 text-white pt-16 pb-24 px-6 relative overflow-hidden">
        <div className="max-w-4xl mx-auto relative z-10">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">
            TOEIC Practice Club
          </h1>
          <p className="text-indigo-100 text-lg md:text-xl max-w-2xl">
            Daily practice for continuous improvement. Solve today's challenge together.
          </p>
        </div>

        {/* Decorative Circles */}
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-indigo-500 rounded-full opacity-50 blur-3xl"></div>
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-72 h-72 bg-indigo-700 rounded-full opacity-50 blur-3xl"></div>
      </div>

      <div className="max-w-4xl mx-auto px-6 -mt-16 relative z-20 space-y-8 pb-16">

        {/* Today's Problem Card */}
        <section>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <Clock className="text-indigo-600" size={24} />
              Today's Problem
            </h2>
            <span className="text-sm font-medium text-slate-500 bg-white px-3 py-1 rounded-full shadow-sm">
              {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}
            </span>
          </div>

          {latestProblemId ? (
            <Link
              href={`/part7/${latestProblemId}`}
              className="block bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden hover:shadow-2xl hover:border-indigo-200 transition-all duration-300 group"
            >
              <div className="p-8 md:p-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
                <div>
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 text-indigo-700 text-xs font-bold uppercase tracking-wider mb-3">
                    Part 7 • Reading
                  </div>
                  <h3 className="text-2xl md:text-3xl font-bold text-slate-900 mb-2 group-hover:text-indigo-600 transition-colors">
                    {latestProblemId}
                  </h3>
                  <p className="text-slate-500">
                    Challenge yourself with the latest reading comprehension problem.
                  </p>
                </div>
                <div className="flex-shrink-0 bg-indigo-600 text-white p-4 rounded-full shadow-lg group-hover:bg-indigo-700 group-hover:scale-110 transition-all duration-300">
                  <ChevronRight size={32} />
                </div>
              </div>
            </Link>
          ) : (
            <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 text-center">
              <p className="text-slate-500">No problems available yet.</p>
            </div>
          )}
        </section>

        {/* Quick Links Grid */}
        <section className="grid md:grid-cols-2 gap-6">
          {/* Part 5 Card */}
          <Link
            href="/part5"
            className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:shadow-md hover:border-blue-300 transition-all group"
          >
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Zap size={24} />
            </div>
            <h3 className="text-lg font-bold text-slate-800 mb-2">Part 5 Practice</h3>
            <p className="text-slate-500 text-sm">
              Quick grammar and vocabulary quizzes generated by AI.
            </p>
          </Link>

          {/* Archive Card */}
          <Link
            href="/part7"
            className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:shadow-md hover:border-emerald-300 transition-all group"
          >
            <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <Archive size={24} />
            </div>
            <h3 className="text-lg font-bold text-slate-800 mb-2">Past Problems</h3>
            <p className="text-slate-500 text-sm">
              Access the full archive of previous Part 7 reading problems.
            </p>
          </Link>
        </section>

      </div>
    </main>
  );
}
